with seed as (
  select *
  from jsonb_to_recordset($$[
    {"title":"Catan","author":"Klaus Teuber","publisher":"Catan Studio","min_players":3,"max_players":4,"play_time_minutes":60,"min_age":10,"complexity":2.3,"category":"Strategy","description":"Trade, build, and settle the island of Catan while competing for victory points.","ownership_status":"owned","cover_url":"https://victorypointlgs.com/cdn/shop/files/cn3081-0_1024x1024.jpg?v=1756150915"},
    {"title":"Catan 5-6 Player Extension","author":"Klaus Teuber","publisher":"Catan Studio","min_players":5,"max_players":6,"play_time_minutes":90,"min_age":10,"complexity":2.4,"category":"Expansion","description":"Adds components and rules to expand Catan for five or six players.","ownership_status":"owned","cover_url":"https://spiedagames.com/cdn/shop/products/catan_5-6_box_art_front_3000x3000.jpg?v=1607057737"},
    {"title":"Catan: Seafarers","author":"Klaus Teuber","publisher":"Catan Studio","min_players":3,"max_players":4,"play_time_minutes":90,"min_age":10,"complexity":2.5,"category":"Expansion","description":"A Catan expansion focused on ships, islands, discovery, and maritime routes.","ownership_status":"owned","cover_url":"https://kosmos-prod.netformic.cloud/Artikel/4002051590055/10099/image-thumb__10099__standardProduct/4002051590055.jpg"},
    {"title":"Splendor","author":"Marc Andre","publisher":"Space Cowboys","min_players":2,"max_players":4,"play_time_minutes":30,"min_age":10,"complexity":1.8,"category":"Strategy","description":"Engine-building gem trading game about collecting tokens and buying development cards.","ownership_status":"owned","cover_url":"https://maskidz.com/cdn/shop/files/71gE0aR85lL._AC_SL1500.jpg?v=1776771480"},
    {"title":"Splendor Duel","author":"Marc Andre, Bruno Cathala","publisher":"Space Cowboys","min_players":2,"max_players":2,"play_time_minutes":30,"min_age":10,"complexity":2.0,"category":"Strategy","description":"Two-player standalone Splendor game with shared token drafting and tactical card play.","ownership_status":"owned","cover_url":"https://www.clubjouet.com/PREXTRA/docs/_thumbnails/Clubjouet/396scspl2p01fren_P.jpg"},
    {"title":"Pit","author":"Edgar Cayce, Harry Gavitt, George S. Parker","publisher":"Winning Moves Games","min_players":3,"max_players":8,"play_time_minutes":30,"min_age":7,"complexity":1.1,"category":"Party Card Game","description":"Fast open-outcry commodity trading card game.","ownership_status":"owned","cover_url":"https://www.boardgamebandit.ca/cdn/shop/products/pit-card-game-standard-edition_1024x1024.jpg?v=1645411619"},
    {"title":"Chess - Magnetic","author":"Traditional","publisher":null,"min_players":2,"max_players":2,"play_time_minutes":30,"min_age":6,"complexity":3.7,"category":"Abstract Strategy","description":"Portable magnetic version of the classic two-player strategy game.","ownership_status":"owned","cover_url":"https://woodexpressions.com/cdn/shop/files/100007-parent_trifold_magnetic_chess_set_main.jpg?v=1768950189"},
    {"title":"Chess - Marble Set from Mexico","author":"Traditional","publisher":null,"min_players":2,"max_players":2,"play_time_minutes":30,"min_age":6,"complexity":3.7,"category":"Abstract Strategy","description":"Decorative marble chess set from Mexico.","ownership_status":"owned","cover_url":"https://images1.novica.net/pictures/7/p46523_2.jpg"},
    {"title":"Chess - Metal Civil War Set","author":"Traditional","publisher":null,"min_players":2,"max_players":2,"play_time_minutes":30,"min_age":14,"complexity":3.7,"category":"Abstract Strategy","description":"Collectible metal chess set with American Civil War themed pieces.","ownership_status":"owned","cover_url":"https://breagans.com/cdn/shop/files/acw-chess-AF.webp?v=1762541855"},
    {"title":"Go - Magnetic","author":"Traditional","publisher":null,"min_players":2,"max_players":2,"play_time_minutes":60,"min_age":8,"complexity":4.0,"category":"Abstract Strategy","description":"Portable magnetic version of Go, the classic territory-control strategy game.","ownership_status":"owned","cover_url":"https://www.go-spiele.de/images/product_images/original_images/12-hv033%20%281%29.jpg"},
    {"title":"Go - Stones and Leather Mat","author":"Traditional","publisher":null,"min_players":2,"max_players":2,"play_time_minutes":60,"min_age":8,"complexity":4.0,"category":"Abstract Strategy","description":"Go stones with a flexible leather or suede mat.","ownership_status":"owned","cover_url":"https://cdn.shopify.com/s/files/1/0085/6159/0323/products/HTB1m.6Xazgy_uJjSZR0xh5K5pXaW_b9ccb7d9-e316-449a-be2e-94939f000bb6_1024x1024.jpg?v=1566056445"},
    {"title":"Go - Wooden Board / Mini Stones","author":"Traditional","publisher":null,"min_players":2,"max_players":2,"play_time_minutes":60,"min_age":8,"complexity":4.0,"category":"Abstract Strategy","description":"Mini Go set with wooden board and small stones.","ownership_status":"owned","cover_url":"https://kurokigoishiten.com/cdn/shop/files/406-8m-05-00.jpg?v=1718856159"},
    {"title":"Playing Cards","author":"Traditional","publisher":null,"min_players":1,"max_players":10,"play_time_minutes":30,"min_age":6,"complexity":1.0,"category":"Card Game","description":"Standard deck for classic card games.","ownership_status":"owned","cover_url":"https://cdn.mall.adeptmind.ai/https%253A%252F%252Ffbres.fivebelow.com%252Fimage%252Fupload%252F5bassets%252Fprod-hts%252Fspree%252Fimages%252F1784980%252Foriginal%252F4445212-00_A.jpg_large.webp"},
    {"title":"Tenzi Dice - 40 Dice","author":"Steve Mark, Kevin Carroll","publisher":"TENZI","min_players":2,"max_players":4,"play_time_minutes":10,"min_age":7,"complexity":1.0,"category":"Dice Game","description":"Fast dice game using forty dice across four player colors.","ownership_status":"owned","cover_url":"https://cdn.open-pr.de/pressemitteilung/9/d/4/9d464ea3.1200x900.jpg"},
    {"title":"Pente","author":"Gary Gabrel","publisher":"Winning Moves Games","min_players":2,"max_players":4,"play_time_minutes":30,"min_age":8,"complexity":2.0,"category":"Abstract Strategy","description":"Five-in-a-row abstract strategy game with pair captures.","ownership_status":"owned","cover_url":"https://i.ebayimg.com/00/s/MTExOVgxNTg1/z/Ut8AAOSwo-tmkaum/%24_3.JPG"},
    {"title":"Forbidden Sky","author":"Matt Leacock","publisher":"Gamewright","min_players":2,"max_players":5,"play_time_minutes":60,"min_age":10,"complexity":2.2,"category":"Cooperative","description":"Cooperative adventure game about wiring a circuit and launching a rocket from a storm platform.","ownership_status":"owned","cover_url":"https://gameknight.ca/cdn/shop/products/Sky-Z_1024x.jpg?v=1588630234"},
    {"title":"Sheriff of Nottingham","author":"Sergio Halaban, Andre Zatz","publisher":"Arcane Wonders","min_players":3,"max_players":5,"play_time_minutes":60,"min_age":14,"complexity":1.7,"category":"Bluffing","description":"Bluffing and negotiation game about smuggling goods past the sheriff.","ownership_status":"owned","cover_url":"https://i.ebayimg.com/images/g/vWoAAOSwH65nY~Nw/s-l2400.jpg"},
    {"title":"Just One","author":"Ludovic Roudy, Bruno Sautter","publisher":"Repos Production","min_players":3,"max_players":7,"play_time_minutes":20,"min_age":8,"complexity":1.0,"category":"Party Word Game","description":"Cooperative word clue game where duplicate clues are cancelled.","ownership_status":"owned","cover_url":"https://www.glasswells.co.uk/images/products/large/2780_4350.jpg"},
    {"title":"UNO Show 'Em No Mercy","author":"Mattel","publisher":"Mattel","min_players":2,"max_players":6,"play_time_minutes":30,"min_age":7,"complexity":1.1,"category":"Card Game","description":"Harsher UNO variant with tougher action cards and stackable penalties.","ownership_status":"owned","cover_url":"https://milagron.com/cdn/shop/files/Mattel-Hwv18-Uno-No-Mercy-Kartlar-7-Yas-Kutu-Oyunlari-1.jpg?v=1742160580&width=1200"},
    {"title":"Exploding Kittens","author":"Elan Lee, Matthew Inman, Shane Small","publisher":"Exploding Kittens","min_players":2,"max_players":5,"play_time_minutes":15,"min_age":7,"complexity":1.1,"category":"Party Card Game","description":"Light push-your-luck card game about avoiding exploding kitten cards.","ownership_status":"owned","cover_url":"https://uk.static.webuy.com/product_images/Gaming/Board%20Games/SBRDEXK01A_l.jpg"},
    {"title":"Unstable Unicorns","author":"Ramsey Nasser","publisher":"Unstable Games","min_players":2,"max_players":8,"play_time_minutes":45,"min_age":14,"complexity":1.5,"category":"Card Game","description":"Take-that card game about building a unicorn stable while disrupting opponents.","ownership_status":"owned","cover_url":"https://vader-prod.s3.amazonaws.com/1759505980-unstable-games-unstable-unicorns-card-game-68dfee2ce3ac8.jpg"},
    {"title":"Bohnanza","author":"Uwe Rosenberg","publisher":"AMIGO","min_players":3,"max_players":7,"play_time_minutes":45,"min_age":12,"complexity":1.7,"category":"Negotiation Card Game","description":"Bean trading and set collection card game with hand-order management.","ownership_status":"owned","cover_url":"https://cdn.shopify.com/s/files/1/0513/4077/1515/products/bohnanza-card-game-amigo-version_1024x1024.jpg?v=1635007561"},
    {"title":"Risk - Antique Hasbro Version","author":"Albert Lamorisse","publisher":"Hasbro","min_players":2,"max_players":6,"play_time_minutes":120,"min_age":10,"complexity":2.1,"category":"Strategy","description":"Classic world-conquest strategy game with area control and dice combat.","ownership_status":"owned","cover_url":"https://tarsasjatekok.com/files/common/c/c2/c2c/c2cf7bff9ad4e9831b5afd03dd08cd82/riziko-a-strategiai-hoditas-tarsasjatek-has34442-14951171936268.jpg"},
    {"title":"Homeworlds","author":"Andy Looney","publisher":"Looney Labs","min_players":2,"max_players":2,"play_time_minutes":45,"min_age":12,"complexity":3.4,"category":"Abstract Strategy","description":"Perfect-information space strategy game using Looney Pyramids.","ownership_status":"owned","cover_url":"https://store.looneylabs.com/cdn/shop/products/88d2f317fd9ef252983e03c9f3f26e14_1200x1200.jpg?v=1596811674"},
    {"title":"Wingspan","author":"Elizabeth Hargrave","publisher":"Stonemaier Games","min_players":1,"max_players":5,"play_time_minutes":70,"min_age":10,"complexity":2.5,"category":"Strategy","description":"Bird-themed engine-building game about attracting birds to habitats.","ownership_status":"owned","cover_url":"https://turnwise.in/cdn/shop/files/Group62_2_1.png?v=1782976847"},
    {"title":"Secret Hitler","author":"Max Temkin, Mike Boxleiter, Tommy Maranges, Macsen Lindsley","publisher":"Goat Wolf and Cabbage","min_players":5,"max_players":10,"play_time_minutes":45,"min_age":13,"complexity":1.7,"category":"Social Deduction","description":"Hidden-role political deduction game of liberals, fascists, and secret identities.","ownership_status":"owned","cover_url":"https://kaissagames.com/pub/media/catalog/product/cache/e1f009a5d1578ed17ef87a6f78739d4f/s/e/secret-hitler-board-game-photoroom.png"},
    {"title":"One Night Ultimate Werewolf","author":"Ted Alspach, Akihisa Okui","publisher":"Bezier Games","min_players":3,"max_players":10,"play_time_minutes":10,"min_age":8,"complexity":1.4,"category":"Social Deduction","description":"Fast hidden-role deduction game played in a single night-and-day round.","ownership_status":"owned","cover_url":"https://lejoueurbeirut.com/cdn/shop/files/onenightw.png?v=1761305031"},
    {"title":"Blood on the Clocktower","author":"Steven Medway","publisher":"The Pandemonium Institute","min_players":5,"max_players":20,"play_time_minutes":120,"min_age":15,"complexity":3.0,"category":"Social Deduction","description":"Large-group social deduction game moderated by a storyteller.","ownership_status":"owned","cover_url":"https://dragonslair.se/thumb/11370/2560x0/Blood-on-the-Clocktower.jpg"},
    {"title":"Flip 7","author":"Eric Olsen","publisher":"The Op Games","min_players":3,"max_players":18,"play_time_minutes":20,"min_age":8,"complexity":1.0,"category":"Card Game","description":"Press-your-luck card game about flipping cards without repeating numbers.","ownership_status":"owned","cover_url":"https://c1-ebgames.eb-cdn.com.au/merchandising/images/packshots/7400c675e31c4f0aa0e5cb1d922f8913_Original.jpg"},
    {"title":"Ticket to Ride","author":"Alan R. Moon","publisher":"Days of Wonder","min_players":2,"max_players":5,"play_time_minutes":60,"min_age":8,"complexity":1.8,"category":"Strategy","description":"Route-building railway game about claiming train routes across a map.","ownership_status":"owned","cover_url":"https://atlasgames.store/cdn/shop/files/do7201-0.jpg?v=1691898682"},
    {"title":"Blokus","author":"Bernard Tavitian","publisher":"Mattel","min_players":2,"max_players":4,"play_time_minutes":20,"min_age":7,"complexity":1.8,"category":"Abstract Strategy","description":"Polyomino placement game about claiming space and blocking opponents.","ownership_status":"owned","cover_url":"https://2.bp.blogspot.com/-UI-u8_jsbko/UJ6-XhKU0zI/AAAAAAAABX8/Oz-Nqo8NbMA/s1600/Blokus_Classic_Board_Games.jpg"},
    {"title":"Cribbage","author":"Traditional","publisher":"Cardinal","min_players":2,"max_players":4,"play_time_minutes":30,"min_age":8,"complexity":2.0,"category":"Card Game","description":"Classic card and pegging game focused on counting combinations.","ownership_status":"owned","cover_url":"https://www.bigw.com.au/medias/sys_master/images/images/h34/h73/120444195110942.jpg"},
    {"title":"Sequence","author":"Doug Reuter","publisher":"Jax","min_players":2,"max_players":12,"play_time_minutes":30,"min_age":7,"complexity":1.3,"category":"Abstract Card Game","description":"Card-and-board strategy game about making rows of chips on matching card spaces. Possibly owned.","ownership_status":"owned","cover_url":"https://eurekapuzzles.com/cdn/shop/products/jaxl8002.jpg?v=1740175815&width=1121"},
    {"title":"Rummikub","author":"Ephraim Hertzano","publisher":"Pressman","min_players":2,"max_players":4,"play_time_minutes":60,"min_age":8,"complexity":1.7,"category":"Tile Game","description":"Rummy-style tile game about creating runs and groups.","ownership_status":"owned","cover_url":"https://stoysnetcdn.com/prmt/prmt040006/prmt040006.jpg"},
    {"title":"Qwirkle","author":"Susan McKinley Ross","publisher":"MindWare","min_players":2,"max_players":4,"play_time_minutes":45,"min_age":6,"complexity":1.6,"category":"Abstract Strategy","description":"Tile-laying game about matching colors and shapes.","ownership_status":"owned","cover_url":"https://www.boardbattle.de/app/uploads/2019/10/qwirkle.jpg"},
    {"title":"Mexican Train Dominoes","author":"Traditional","publisher":"Goliath","min_players":1,"max_players":8,"play_time_minutes":30,"min_age":6,"complexity":1.2,"category":"Dominoes","description":"Domino game using double-twelve dominoes and shared train routes.","ownership_status":"owned","cover_url":"https://image.smythstoys.com/original/800/desktop/219938.jpg"},
    {"title":"Bananagrams","author":"Rena Nathanson, Abe Nathanson","publisher":"Bananagrams","min_players":1,"max_players":8,"play_time_minutes":15,"min_age":7,"complexity":1.3,"category":"Word Game","description":"Fast real-time word tile game played without a board.","ownership_status":"owned","cover_url":"https://twentysidedstore.com/cdn/shop/products/Bananagrams_1200x1200.png?v=1571446667"},
    {"title":"Scrabble","author":"Alfred Mosher Butts","publisher":"Mattel","min_players":2,"max_players":4,"play_time_minutes":90,"min_age":10,"complexity":2.1,"category":"Word Game","description":"Classic crossword-style word game using letter tiles and premium board spaces.","ownership_status":"owned","cover_url":"https://www.tunisiejouets.com/wp-content/uploads/2025/01/1000053341.jpg"},
    {"title":"Codenames","author":"Vlaada Chvatil","publisher":"Czech Games Edition","min_players":2,"max_players":8,"play_time_minutes":15,"min_age":10,"complexity":1.3,"category":"Party Word Game","description":"Team word-association deduction game with spymasters giving one-word clues.","ownership_status":"owned","cover_url":"https://i5.walmartimages.cl/asr/7886adb3-5df3-4984-8578-c42a8b53f60c.e756d8786dd7ddff9286971553c9bb5e.jpeg?odnBg=ffffff&odnHeight=2000&odnWidth=2000"},
    {"title":"Poetry for Neanderthals","author":"Brian Spence","publisher":"Exploding Kittens","min_players":2,"max_players":12,"play_time_minutes":15,"min_age":7,"complexity":1.0,"category":"Party Word Game","description":"Word guessing party game where clues must use one-syllable words.","ownership_status":"owned","cover_url":"https://momogadgets.com/cdn/shop/files/poetry-for-neanderthals-by-exploding-kittens-card-games-for-adults-teens-and-kids-momo-gadgets-6-35606658220325.jpg?v=1721123724"},
    {"title":"Love Letter","author":"Seiji Kanai","publisher":"Z-Man Games","min_players":2,"max_players":6,"play_time_minutes":20,"min_age":10,"complexity":1.2,"category":"Card Game","description":"Compact deduction and hand-management card game about delivering a letter to the princess.","ownership_status":"owned","cover_url":"https://cdn.svc.asmodee.net/production-asmodeeca/uploads/image-converter/2025/03/ZMGLLS0101EN-LOVE_LETTER-EN-3D_RIGHT-1024x1024.webp"},
    {"title":"Coup","author":"Rikki Tahta","publisher":"Indie Boards and Cards","min_players":2,"max_players":6,"play_time_minutes":15,"min_age":13,"complexity":1.4,"category":"Bluffing Card Game","description":"Hidden-influence bluffing game set in The Resistance universe.","ownership_status":"owned","cover_url":"https://cdn.shoplightspeed.com/shops/638106/files/23907785/1652x1652x2/indie-boards-cards-coup.jpg"},
    {"title":"Betrayal at House on the Hill","author":"Rob Daviau, Bruce Glassco, Bill McQuillan, Mike Selinker, Teeuwynn Woodruff","publisher":"Avalon Hill","min_players":3,"max_players":6,"play_time_minutes":60,"min_age":12,"complexity":2.4,"category":"Horror Adventure","description":"Haunted-house exploration game where one player may become the traitor.","ownership_status":"owned","cover_url":"https://twentysidedstore.com/cdn/shop/products/174_20221004_betrayal-at-house-on-the-hill_1_512x512.jpg?v=1664918031"},
    {"title":"Clue - Harry Potter Edition","author":"Rob Daviau","publisher":"The Op Games","min_players":3,"max_players":5,"play_time_minutes":45,"min_age":9,"complexity":1.7,"category":"Deduction","description":"Harry Potter themed edition of Clue with a moving Hogwarts board.","ownership_status":"owned","cover_url":"https://twentysidedstore.com/cdn/shop/products/ClueHarryPotter_1024x1024.png?v=1612300741"},
    {"title":"Rivals for Catan","author":"Klaus Teuber","publisher":"Catan Studio","min_players":2,"max_players":2,"play_time_minutes":45,"min_age":10,"complexity":2.3,"category":"Card Game","description":"Two-player Catan card game about developing rival principalities.","ownership_status":"owned","cover_url":"https://cdn11.bigcommerce.com/s-285hkc2e8r/products/24963/images/251370/cn3131_0__56979.1719407222.500.750.jpg?c=2"},
    {"title":"Rivals for Catan - Expansion","author":"Klaus Teuber","publisher":"Catan Studio","min_players":2,"max_players":2,"play_time_minutes":60,"min_age":10,"complexity":2.6,"category":"Expansion","description":"Expansion content for Rivals for Catan, represented by Age of Darkness.","ownership_status":"owned","cover_url":"https://assets.woolworths.com.au/images/1005/1116241227.jpg?h=600&impolicy=wowsmkqiema&w=600"},
    {"title":"Skull King","author":"Brent Beck","publisher":"Grandpa Beck's Games","min_players":2,"max_players":8,"play_time_minutes":30,"min_age":8,"complexity":1.4,"category":"Trick-Taking Card Game","description":"Pirate-themed trick-taking game with bidding and special cards.","ownership_status":"owned","cover_url":"https://hivegames.at/wp-content/uploads/2024/01/7176_1_skull_king_-_de_ravensburger_866d5828.jpg"},
    {"title":"Cover Your Assets","author":"Brent Beck","publisher":"Grandpa Beck's Games","min_players":2,"max_players":6,"play_time_minutes":30,"min_age":7,"complexity":1.1,"category":"Card Game","description":"Set-collection card game about building and stealing stacks of assets.","ownership_status":"owned","cover_url":"https://static.wixstatic.com/media/d0f032_d2245562994242dd9834680d3b173f23~mv2.jpg/v1/fill/w_980%2Ch_1455%2Cal_c%2Cq_85%2Cusm_0.66_1.00_0.01%2Cenc_auto/d0f032_d2245562994242dd9834680d3b173f23~mv2.jpg"},
    {"title":"Poker Chip Set","author":"Traditional","publisher":null,"min_players":2,"max_players":10,"play_time_minutes":60,"min_age":12,"complexity":1.5,"category":"Card Game Accessory","description":"Poker chips and case for poker and other betting-style card games.","ownership_status":"owned","cover_url":"https://mobileimages.lowes.com/productimages/a1d102cd-1a7f-42ff-b1c4-429c441c8344/66791317.jpeg?size=pdhism"},
    {"title":"Bang!","author":"Emiliano Sciarra","publisher":"DV Games","min_players":3,"max_players":8,"play_time_minutes":30,"min_age":8,"complexity":1.6,"category":"Hidden Role Card Game","description":"Wild West hidden-role card game of sheriffs, outlaws, deputies, and renegades.","ownership_status":"owned","cover_url":"https://bibliojeu.net/images/bang/bang.jpg"},
    {"title":"Carcassonne","author":"Klaus-Jurgen Wrede","publisher":"Z-Man Games","min_players":2,"max_players":5,"play_time_minutes":45,"min_age":7,"complexity":1.9,"category":"Tile Placement","description":"Medieval tile-placement game about cities, roads, monasteries, and farms.","ownership_status":"wishlist","cover_url":"https://media.cdnws.com/_i/184339/3373/894/76/carcassonne-boite.jpeg"},
    {"title":"Azul","author":"Michael Kiesling","publisher":"Plan B Games","min_players":2,"max_players":4,"play_time_minutes":45,"min_age":8,"complexity":1.8,"category":"Abstract Strategy","description":"Tile-drafting pattern-building game inspired by Portuguese azulejo tiles.","ownership_status":"wishlist","cover_url":"https://cdn.shoplightspeed.com/shops/636231/files/68363129/1652x1652x2/plan-b-games-azul.jpg"},
    {"title":"7 Wonders","author":"Antoine Bauza","publisher":"Repos Production","min_players":2,"max_players":7,"play_time_minutes":30,"min_age":10,"complexity":2.3,"category":"Strategy","description":"Civilization card-drafting game about building an ancient wonder.","ownership_status":"wishlist","cover_url":"https://www.myludo.fr/img/jeux/1709818397/jpg/ae/4680.jpg"},
    {"title":"Hive","author":"John Yianni","publisher":"Smart Zone Games","min_players":2,"max_players":2,"play_time_minutes":20,"min_age":9,"complexity":2.3,"category":"Abstract Strategy","description":"Boardless abstract strategy game using insect tiles to surround the opposing queen.","ownership_status":"wishlist","cover_url":"https://cdn.shoplightspeed.com/shops/636231/files/20716066/smart-zone-games-hive-a-game-crawling-with-possibi.jpg"},
    {"title":"Mancala","author":"Traditional","publisher":"Cardinal","min_players":2,"max_players":2,"play_time_minutes":15,"min_age":8,"complexity":1.5,"category":"Abstract Strategy","description":"Traditional count-and-capture game played with stones and rows of pits.","ownership_status":"wishlist","cover_url":"https://i5.walmartimages.com/asr/cfec4fee-e496-4fbc-9985-b432339ed6d5.830f7aaf3326b3ba6494c536410326f9.jpeg?odnBg=FFFFFF&odnHeight=768&odnWidth=768"},
    {"title":"Five Crowns","author":"Marsha J. Falco","publisher":"Set Enterprises","min_players":1,"max_players":7,"play_time_minutes":45,"min_age":8,"complexity":1.2,"category":"Card Game","description":"Five-suited rummy-style card game where wild cards change each round.","ownership_status":"wishlist","cover_url":"https://images.thalia.media/07/-/d582c0b7b361401098202fe1333aff44/five-crowns.jpeg"},
    {"title":"Phase 10","author":"Kenneth Johnson","publisher":"Mattel","min_players":2,"max_players":6,"play_time_minutes":45,"min_age":7,"complexity":1.2,"category":"Card Game","description":"Rummy-style card game about completing ten phases of sets and runs.","ownership_status":"wishlist","cover_url":"https://i2.wp.com/i5.walmartimages.com/asr/ed1f93f9-8201-4cf2-b366-8535c3dffb44.4d5d066061f2ce9798d0868785dc2ebc.jpeg?odnBg=ffffff&odnHeight=1000&odnWidth=1000"},
    {"title":"Spot It!","author":"Denis Blanchot, Jacques Cottereau","publisher":"Zygomatic","min_players":2,"max_players":8,"play_time_minutes":15,"min_age":6,"complexity":1.0,"category":"Party Card Game","description":"Fast visual matching game where every pair of cards shares exactly one symbol.","ownership_status":"wishlist","cover_url":"https://www.bigw.com.au/medias/sys_master/images/images/hf7/hd7/105137534271518.jpg"},
    {"title":"Taco Cat Goat Cheese Pizza","author":"Dave Campbell","publisher":"Dolphin Hat Games","min_players":2,"max_players":8,"play_time_minutes":10,"min_age":8,"complexity":1.0,"category":"Party Card Game","description":"Fast slap-and-match party card game built around a repeating phrase.","ownership_status":"wishlist","cover_url":"https://image.bog-ide.dk/3948395-1467624-1000-787/webp/0/1000/3948395-1467624-1000-787.webp"}
  ]$$::jsonb) as item(
    title text,
    author text,
    publisher text,
    min_players integer,
    max_players integer,
    play_time_minutes integer,
    min_age integer,
    complexity numeric,
    category text,
    description text,
    ownership_status text,
    cover_url text
  )
),
target_library as (
  select id as library_id
  from library.libraries
  where slug = 'jenkins'
)
update library.books books
set
  title = seed.title,
  author = seed.author,
  genre = seed.category,
  description = seed.description,
  cover_url = seed.cover_url,
  ownership_status = seed.ownership_status,
  media_type = 'board_game',
  publisher = seed.publisher,
  min_players = seed.min_players,
  max_players = seed.max_players,
  play_time_minutes = seed.play_time_minutes,
  min_age = seed.min_age,
  complexity = seed.complexity,
  category = seed.category,
  updated_at = now()
from seed, target_library
where books.library_id = target_library.library_id
  and books.media_type = 'board_game'
  and books.deleted_at is null
  and (
    lower(books.title) = lower(seed.title)
    or (books.title = 'Settlers of Catan' and seed.title = 'Catan')
    or (books.title = 'Chess' and seed.title = 'Chess - Magnetic')
  );

with seed as (
  select *
  from jsonb_to_recordset($$[
    {"title":"Catan","author":"Klaus Teuber","publisher":"Catan Studio","min_players":3,"max_players":4,"play_time_minutes":60,"min_age":10,"complexity":2.3,"category":"Strategy","description":"Trade, build, and settle the island of Catan while competing for victory points.","ownership_status":"owned","cover_url":"https://victorypointlgs.com/cdn/shop/files/cn3081-0_1024x1024.jpg?v=1756150915"},
    {"title":"Catan 5-6 Player Extension","author":"Klaus Teuber","publisher":"Catan Studio","min_players":5,"max_players":6,"play_time_minutes":90,"min_age":10,"complexity":2.4,"category":"Expansion","description":"Adds components and rules to expand Catan for five or six players.","ownership_status":"owned","cover_url":"https://spiedagames.com/cdn/shop/products/catan_5-6_box_art_front_3000x3000.jpg?v=1607057737"},
    {"title":"Catan: Seafarers","author":"Klaus Teuber","publisher":"Catan Studio","min_players":3,"max_players":4,"play_time_minutes":90,"min_age":10,"complexity":2.5,"category":"Expansion","description":"A Catan expansion focused on ships, islands, discovery, and maritime routes.","ownership_status":"owned","cover_url":"https://kosmos-prod.netformic.cloud/Artikel/4002051590055/10099/image-thumb__10099__standardProduct/4002051590055.jpg"},
    {"title":"Splendor","author":"Marc Andre","publisher":"Space Cowboys","min_players":2,"max_players":4,"play_time_minutes":30,"min_age":10,"complexity":1.8,"category":"Strategy","description":"Engine-building gem trading game about collecting tokens and buying development cards.","ownership_status":"owned","cover_url":"https://maskidz.com/cdn/shop/files/71gE0aR85lL._AC_SL1500.jpg?v=1776771480"},
    {"title":"Splendor Duel","author":"Marc Andre, Bruno Cathala","publisher":"Space Cowboys","min_players":2,"max_players":2,"play_time_minutes":30,"min_age":10,"complexity":2.0,"category":"Strategy","description":"Two-player standalone Splendor game with shared token drafting and tactical card play.","ownership_status":"owned","cover_url":"https://www.clubjouet.com/PREXTRA/docs/_thumbnails/Clubjouet/396scspl2p01fren_P.jpg"},
    {"title":"Pit","author":"Edgar Cayce, Harry Gavitt, George S. Parker","publisher":"Winning Moves Games","min_players":3,"max_players":8,"play_time_minutes":30,"min_age":7,"complexity":1.1,"category":"Party Card Game","description":"Fast open-outcry commodity trading card game.","ownership_status":"owned","cover_url":"https://www.boardgamebandit.ca/cdn/shop/products/pit-card-game-standard-edition_1024x1024.jpg?v=1645411619"},
    {"title":"Chess - Magnetic","author":"Traditional","publisher":null,"min_players":2,"max_players":2,"play_time_minutes":30,"min_age":6,"complexity":3.7,"category":"Abstract Strategy","description":"Portable magnetic version of the classic two-player strategy game.","ownership_status":"owned","cover_url":"https://woodexpressions.com/cdn/shop/files/100007-parent_trifold_magnetic_chess_set_main.jpg?v=1768950189"},
    {"title":"Chess - Marble Set from Mexico","author":"Traditional","publisher":null,"min_players":2,"max_players":2,"play_time_minutes":30,"min_age":6,"complexity":3.7,"category":"Abstract Strategy","description":"Decorative marble chess set from Mexico.","ownership_status":"owned","cover_url":"https://images1.novica.net/pictures/7/p46523_2.jpg"},
    {"title":"Chess - Metal Civil War Set","author":"Traditional","publisher":null,"min_players":2,"max_players":2,"play_time_minutes":30,"min_age":14,"complexity":3.7,"category":"Abstract Strategy","description":"Collectible metal chess set with American Civil War themed pieces.","ownership_status":"owned","cover_url":"https://breagans.com/cdn/shop/files/acw-chess-AF.webp?v=1762541855"},
    {"title":"Go - Magnetic","author":"Traditional","publisher":null,"min_players":2,"max_players":2,"play_time_minutes":60,"min_age":8,"complexity":4.0,"category":"Abstract Strategy","description":"Portable magnetic version of Go, the classic territory-control strategy game.","ownership_status":"owned","cover_url":"https://www.go-spiele.de/images/product_images/original_images/12-hv033%20%281%29.jpg"},
    {"title":"Go - Stones and Leather Mat","author":"Traditional","publisher":null,"min_players":2,"max_players":2,"play_time_minutes":60,"min_age":8,"complexity":4.0,"category":"Abstract Strategy","description":"Go stones with a flexible leather or suede mat.","ownership_status":"owned","cover_url":"https://cdn.shopify.com/s/files/1/0085/6159/0323/products/HTB1m.6Xazgy_uJjSZR0xh5K5pXaW_b9ccb7d9-e316-449a-be2e-94939f000bb6_1024x1024.jpg?v=1566056445"},
    {"title":"Go - Wooden Board / Mini Stones","author":"Traditional","publisher":null,"min_players":2,"max_players":2,"play_time_minutes":60,"min_age":8,"complexity":4.0,"category":"Abstract Strategy","description":"Mini Go set with wooden board and small stones.","ownership_status":"owned","cover_url":"https://kurokigoishiten.com/cdn/shop/files/406-8m-05-00.jpg?v=1718856159"},
    {"title":"Playing Cards","author":"Traditional","publisher":null,"min_players":1,"max_players":10,"play_time_minutes":30,"min_age":6,"complexity":1.0,"category":"Card Game","description":"Standard deck for classic card games.","ownership_status":"owned","cover_url":"https://cdn.mall.adeptmind.ai/https%253A%252F%252Ffbres.fivebelow.com%252Fimage%252Fupload%252F5bassets%252Fprod-hts%252Fspree%252Fimages%252F1784980%252Foriginal%252F4445212-00_A.jpg_large.webp"},
    {"title":"Tenzi Dice - 40 Dice","author":"Steve Mark, Kevin Carroll","publisher":"TENZI","min_players":2,"max_players":4,"play_time_minutes":10,"min_age":7,"complexity":1.0,"category":"Dice Game","description":"Fast dice game using forty dice across four player colors.","ownership_status":"owned","cover_url":"https://cdn.open-pr.de/pressemitteilung/9/d/4/9d464ea3.1200x900.jpg"},
    {"title":"Pente","author":"Gary Gabrel","publisher":"Winning Moves Games","min_players":2,"max_players":4,"play_time_minutes":30,"min_age":8,"complexity":2.0,"category":"Abstract Strategy","description":"Five-in-a-row abstract strategy game with pair captures.","ownership_status":"owned","cover_url":"https://i.ebayimg.com/00/s/MTExOVgxNTg1/z/Ut8AAOSwo-tmkaum/%24_3.JPG"},
    {"title":"Forbidden Sky","author":"Matt Leacock","publisher":"Gamewright","min_players":2,"max_players":5,"play_time_minutes":60,"min_age":10,"complexity":2.2,"category":"Cooperative","description":"Cooperative adventure game about wiring a circuit and launching a rocket from a storm platform.","ownership_status":"owned","cover_url":"https://gameknight.ca/cdn/shop/products/Sky-Z_1024x.jpg?v=1588630234"},
    {"title":"Sheriff of Nottingham","author":"Sergio Halaban, Andre Zatz","publisher":"Arcane Wonders","min_players":3,"max_players":5,"play_time_minutes":60,"min_age":14,"complexity":1.7,"category":"Bluffing","description":"Bluffing and negotiation game about smuggling goods past the sheriff.","ownership_status":"owned","cover_url":"https://i.ebayimg.com/images/g/vWoAAOSwH65nY~Nw/s-l2400.jpg"},
    {"title":"Just One","author":"Ludovic Roudy, Bruno Sautter","publisher":"Repos Production","min_players":3,"max_players":7,"play_time_minutes":20,"min_age":8,"complexity":1.0,"category":"Party Word Game","description":"Cooperative word clue game where duplicate clues are cancelled.","ownership_status":"owned","cover_url":"https://www.glasswells.co.uk/images/products/large/2780_4350.jpg"},
    {"title":"UNO Show 'Em No Mercy","author":"Mattel","publisher":"Mattel","min_players":2,"max_players":6,"play_time_minutes":30,"min_age":7,"complexity":1.1,"category":"Card Game","description":"Harsher UNO variant with tougher action cards and stackable penalties.","ownership_status":"owned","cover_url":"https://milagron.com/cdn/shop/files/Mattel-Hwv18-Uno-No-Mercy-Kartlar-7-Yas-Kutu-Oyunlari-1.jpg?v=1742160580&width=1200"},
    {"title":"Exploding Kittens","author":"Elan Lee, Matthew Inman, Shane Small","publisher":"Exploding Kittens","min_players":2,"max_players":5,"play_time_minutes":15,"min_age":7,"complexity":1.1,"category":"Party Card Game","description":"Light push-your-luck card game about avoiding exploding kitten cards.","ownership_status":"owned","cover_url":"https://uk.static.webuy.com/product_images/Gaming/Board%20Games/SBRDEXK01A_l.jpg"},
    {"title":"Unstable Unicorns","author":"Ramsey Nasser","publisher":"Unstable Games","min_players":2,"max_players":8,"play_time_minutes":45,"min_age":14,"complexity":1.5,"category":"Card Game","description":"Take-that card game about building a unicorn stable while disrupting opponents.","ownership_status":"owned","cover_url":"https://vader-prod.s3.amazonaws.com/1759505980-unstable-games-unstable-unicorns-card-game-68dfee2ce3ac8.jpg"},
    {"title":"Bohnanza","author":"Uwe Rosenberg","publisher":"AMIGO","min_players":3,"max_players":7,"play_time_minutes":45,"min_age":12,"complexity":1.7,"category":"Negotiation Card Game","description":"Bean trading and set collection card game with hand-order management.","ownership_status":"owned","cover_url":"https://cdn.shopify.com/s/files/1/0513/4077/1515/products/bohnanza-card-game-amigo-version_1024x1024.jpg?v=1635007561"},
    {"title":"Risk - Antique Hasbro Version","author":"Albert Lamorisse","publisher":"Hasbro","min_players":2,"max_players":6,"play_time_minutes":120,"min_age":10,"complexity":2.1,"category":"Strategy","description":"Classic world-conquest strategy game with area control and dice combat.","ownership_status":"owned","cover_url":"https://tarsasjatekok.com/files/common/c/c2/c2c/c2cf7bff9ad4e9831b5afd03dd08cd82/riziko-a-strategiai-hoditas-tarsasjatek-has34442-14951171936268.jpg"},
    {"title":"Homeworlds","author":"Andy Looney","publisher":"Looney Labs","min_players":2,"max_players":2,"play_time_minutes":45,"min_age":12,"complexity":3.4,"category":"Abstract Strategy","description":"Perfect-information space strategy game using Looney Pyramids.","ownership_status":"owned","cover_url":"https://store.looneylabs.com/cdn/shop/products/88d2f317fd9ef252983e03c9f3f26e14_1200x1200.jpg?v=1596811674"},
    {"title":"Wingspan","author":"Elizabeth Hargrave","publisher":"Stonemaier Games","min_players":1,"max_players":5,"play_time_minutes":70,"min_age":10,"complexity":2.5,"category":"Strategy","description":"Bird-themed engine-building game about attracting birds to habitats.","ownership_status":"owned","cover_url":"https://turnwise.in/cdn/shop/files/Group62_2_1.png?v=1782976847"},
    {"title":"Secret Hitler","author":"Max Temkin, Mike Boxleiter, Tommy Maranges, Macsen Lindsley","publisher":"Goat Wolf and Cabbage","min_players":5,"max_players":10,"play_time_minutes":45,"min_age":13,"complexity":1.7,"category":"Social Deduction","description":"Hidden-role political deduction game of liberals, fascists, and secret identities.","ownership_status":"owned","cover_url":"https://kaissagames.com/pub/media/catalog/product/cache/e1f009a5d1578ed17ef87a6f78739d4f/s/e/secret-hitler-board-game-photoroom.png"},
    {"title":"One Night Ultimate Werewolf","author":"Ted Alspach, Akihisa Okui","publisher":"Bezier Games","min_players":3,"max_players":10,"play_time_minutes":10,"min_age":8,"complexity":1.4,"category":"Social Deduction","description":"Fast hidden-role deduction game played in a single night-and-day round.","ownership_status":"owned","cover_url":"https://lejoueurbeirut.com/cdn/shop/files/onenightw.png?v=1761305031"},
    {"title":"Blood on the Clocktower","author":"Steven Medway","publisher":"The Pandemonium Institute","min_players":5,"max_players":20,"play_time_minutes":120,"min_age":15,"complexity":3.0,"category":"Social Deduction","description":"Large-group social deduction game moderated by a storyteller.","ownership_status":"owned","cover_url":"https://dragonslair.se/thumb/11370/2560x0/Blood-on-the-Clocktower.jpg"},
    {"title":"Flip 7","author":"Eric Olsen","publisher":"The Op Games","min_players":3,"max_players":18,"play_time_minutes":20,"min_age":8,"complexity":1.0,"category":"Card Game","description":"Press-your-luck card game about flipping cards without repeating numbers.","ownership_status":"owned","cover_url":"https://c1-ebgames.eb-cdn.com.au/merchandising/images/packshots/7400c675e31c4f0aa0e5cb1d922f8913_Original.jpg"},
    {"title":"Ticket to Ride","author":"Alan R. Moon","publisher":"Days of Wonder","min_players":2,"max_players":5,"play_time_minutes":60,"min_age":8,"complexity":1.8,"category":"Strategy","description":"Route-building railway game about claiming train routes across a map.","ownership_status":"owned","cover_url":"https://atlasgames.store/cdn/shop/files/do7201-0.jpg?v=1691898682"},
    {"title":"Blokus","author":"Bernard Tavitian","publisher":"Mattel","min_players":2,"max_players":4,"play_time_minutes":20,"min_age":7,"complexity":1.8,"category":"Abstract Strategy","description":"Polyomino placement game about claiming space and blocking opponents.","ownership_status":"owned","cover_url":"https://2.bp.blogspot.com/-UI-u8_jsbko/UJ6-XhKU0zI/AAAAAAAABX8/Oz-Nqo8NbMA/s1600/Blokus_Classic_Board_Games.jpg"},
    {"title":"Cribbage","author":"Traditional","publisher":"Cardinal","min_players":2,"max_players":4,"play_time_minutes":30,"min_age":8,"complexity":2.0,"category":"Card Game","description":"Classic card and pegging game focused on counting combinations.","ownership_status":"owned","cover_url":"https://www.bigw.com.au/medias/sys_master/images/images/h34/h73/120444195110942.jpg"},
    {"title":"Sequence","author":"Doug Reuter","publisher":"Jax","min_players":2,"max_players":12,"play_time_minutes":30,"min_age":7,"complexity":1.3,"category":"Abstract Card Game","description":"Card-and-board strategy game about making rows of chips on matching card spaces. Possibly owned.","ownership_status":"owned","cover_url":"https://eurekapuzzles.com/cdn/shop/products/jaxl8002.jpg?v=1740175815&width=1121"},
    {"title":"Rummikub","author":"Ephraim Hertzano","publisher":"Pressman","min_players":2,"max_players":4,"play_time_minutes":60,"min_age":8,"complexity":1.7,"category":"Tile Game","description":"Rummy-style tile game about creating runs and groups.","ownership_status":"owned","cover_url":"https://stoysnetcdn.com/prmt/prmt040006/prmt040006.jpg"},
    {"title":"Qwirkle","author":"Susan McKinley Ross","publisher":"MindWare","min_players":2,"max_players":4,"play_time_minutes":45,"min_age":6,"complexity":1.6,"category":"Abstract Strategy","description":"Tile-laying game about matching colors and shapes.","ownership_status":"owned","cover_url":"https://www.boardbattle.de/app/uploads/2019/10/qwirkle.jpg"},
    {"title":"Mexican Train Dominoes","author":"Traditional","publisher":"Goliath","min_players":1,"max_players":8,"play_time_minutes":30,"min_age":6,"complexity":1.2,"category":"Dominoes","description":"Domino game using double-twelve dominoes and shared train routes.","ownership_status":"owned","cover_url":"https://image.smythstoys.com/original/800/desktop/219938.jpg"},
    {"title":"Bananagrams","author":"Rena Nathanson, Abe Nathanson","publisher":"Bananagrams","min_players":1,"max_players":8,"play_time_minutes":15,"min_age":7,"complexity":1.3,"category":"Word Game","description":"Fast real-time word tile game played without a board.","ownership_status":"owned","cover_url":"https://twentysidedstore.com/cdn/shop/products/Bananagrams_1200x1200.png?v=1571446667"},
    {"title":"Scrabble","author":"Alfred Mosher Butts","publisher":"Mattel","min_players":2,"max_players":4,"play_time_minutes":90,"min_age":10,"complexity":2.1,"category":"Word Game","description":"Classic crossword-style word game using letter tiles and premium board spaces.","ownership_status":"owned","cover_url":"https://www.tunisiejouets.com/wp-content/uploads/2025/01/1000053341.jpg"},
    {"title":"Codenames","author":"Vlaada Chvatil","publisher":"Czech Games Edition","min_players":2,"max_players":8,"play_time_minutes":15,"min_age":10,"complexity":1.3,"category":"Party Word Game","description":"Team word-association deduction game with spymasters giving one-word clues.","ownership_status":"owned","cover_url":"https://i5.walmartimages.cl/asr/7886adb3-5df3-4984-8578-c42a8b53f60c.e756d8786dd7ddff9286971553c9bb5e.jpeg?odnBg=ffffff&odnHeight=2000&odnWidth=2000"},
    {"title":"Poetry for Neanderthals","author":"Brian Spence","publisher":"Exploding Kittens","min_players":2,"max_players":12,"play_time_minutes":15,"min_age":7,"complexity":1.0,"category":"Party Word Game","description":"Word guessing party game where clues must use one-syllable words.","ownership_status":"owned","cover_url":"https://momogadgets.com/cdn/shop/files/poetry-for-neanderthals-by-exploding-kittens-card-games-for-adults-teens-and-kids-momo-gadgets-6-35606658220325.jpg?v=1721123724"},
    {"title":"Love Letter","author":"Seiji Kanai","publisher":"Z-Man Games","min_players":2,"max_players":6,"play_time_minutes":20,"min_age":10,"complexity":1.2,"category":"Card Game","description":"Compact deduction and hand-management card game about delivering a letter to the princess.","ownership_status":"owned","cover_url":"https://cdn.svc.asmodee.net/production-asmodeeca/uploads/image-converter/2025/03/ZMGLLS0101EN-LOVE_LETTER-EN-3D_RIGHT-1024x1024.webp"},
    {"title":"Coup","author":"Rikki Tahta","publisher":"Indie Boards and Cards","min_players":2,"max_players":6,"play_time_minutes":15,"min_age":13,"complexity":1.4,"category":"Bluffing Card Game","description":"Hidden-influence bluffing game set in The Resistance universe.","ownership_status":"owned","cover_url":"https://cdn.shoplightspeed.com/shops/638106/files/23907785/1652x1652x2/indie-boards-cards-coup.jpg"},
    {"title":"Betrayal at House on the Hill","author":"Rob Daviau, Bruce Glassco, Bill McQuillan, Mike Selinker, Teeuwynn Woodruff","publisher":"Avalon Hill","min_players":3,"max_players":6,"play_time_minutes":60,"min_age":12,"complexity":2.4,"category":"Horror Adventure","description":"Haunted-house exploration game where one player may become the traitor.","ownership_status":"owned","cover_url":"https://twentysidedstore.com/cdn/shop/products/174_20221004_betrayal-at-house-on-the-hill_1_512x512.jpg?v=1664918031"},
    {"title":"Clue - Harry Potter Edition","author":"Rob Daviau","publisher":"The Op Games","min_players":3,"max_players":5,"play_time_minutes":45,"min_age":9,"complexity":1.7,"category":"Deduction","description":"Harry Potter themed edition of Clue with a moving Hogwarts board.","ownership_status":"owned","cover_url":"https://twentysidedstore.com/cdn/shop/products/ClueHarryPotter_1024x1024.png?v=1612300741"},
    {"title":"Rivals for Catan","author":"Klaus Teuber","publisher":"Catan Studio","min_players":2,"max_players":2,"play_time_minutes":45,"min_age":10,"complexity":2.3,"category":"Card Game","description":"Two-player Catan card game about developing rival principalities.","ownership_status":"owned","cover_url":"https://cdn11.bigcommerce.com/s-285hkc2e8r/products/24963/images/251370/cn3131_0__56979.1719407222.500.750.jpg?c=2"},
    {"title":"Rivals for Catan - Expansion","author":"Klaus Teuber","publisher":"Catan Studio","min_players":2,"max_players":2,"play_time_minutes":60,"min_age":10,"complexity":2.6,"category":"Expansion","description":"Expansion content for Rivals for Catan, represented by Age of Darkness.","ownership_status":"owned","cover_url":"https://assets.woolworths.com.au/images/1005/1116241227.jpg?h=600&impolicy=wowsmkqiema&w=600"},
    {"title":"Skull King","author":"Brent Beck","publisher":"Grandpa Beck's Games","min_players":2,"max_players":8,"play_time_minutes":30,"min_age":8,"complexity":1.4,"category":"Trick-Taking Card Game","description":"Pirate-themed trick-taking game with bidding and special cards.","ownership_status":"owned","cover_url":"https://hivegames.at/wp-content/uploads/2024/01/7176_1_skull_king_-_de_ravensburger_866d5828.jpg"},
    {"title":"Cover Your Assets","author":"Brent Beck","publisher":"Grandpa Beck's Games","min_players":2,"max_players":6,"play_time_minutes":30,"min_age":7,"complexity":1.1,"category":"Card Game","description":"Set-collection card game about building and stealing stacks of assets.","ownership_status":"owned","cover_url":"https://static.wixstatic.com/media/d0f032_d2245562994242dd9834680d3b173f23~mv2.jpg/v1/fill/w_980%2Ch_1455%2Cal_c%2Cq_85%2Cusm_0.66_1.00_0.01%2Cenc_auto/d0f032_d2245562994242dd9834680d3b173f23~mv2.jpg"},
    {"title":"Poker Chip Set","author":"Traditional","publisher":null,"min_players":2,"max_players":10,"play_time_minutes":60,"min_age":12,"complexity":1.5,"category":"Card Game Accessory","description":"Poker chips and case for poker and other betting-style card games.","ownership_status":"owned","cover_url":"https://mobileimages.lowes.com/productimages/a1d102cd-1a7f-42ff-b1c4-429c441c8344/66791317.jpeg?size=pdhism"},
    {"title":"Bang!","author":"Emiliano Sciarra","publisher":"DV Games","min_players":3,"max_players":8,"play_time_minutes":30,"min_age":8,"complexity":1.6,"category":"Hidden Role Card Game","description":"Wild West hidden-role card game of sheriffs, outlaws, deputies, and renegades.","ownership_status":"owned","cover_url":"https://bibliojeu.net/images/bang/bang.jpg"},
    {"title":"Carcassonne","author":"Klaus-Jurgen Wrede","publisher":"Z-Man Games","min_players":2,"max_players":5,"play_time_minutes":45,"min_age":7,"complexity":1.9,"category":"Tile Placement","description":"Medieval tile-placement game about cities, roads, monasteries, and farms.","ownership_status":"wishlist","cover_url":"https://media.cdnws.com/_i/184339/3373/894/76/carcassonne-boite.jpeg"},
    {"title":"Azul","author":"Michael Kiesling","publisher":"Plan B Games","min_players":2,"max_players":4,"play_time_minutes":45,"min_age":8,"complexity":1.8,"category":"Abstract Strategy","description":"Tile-drafting pattern-building game inspired by Portuguese azulejo tiles.","ownership_status":"wishlist","cover_url":"https://cdn.shoplightspeed.com/shops/636231/files/68363129/1652x1652x2/plan-b-games-azul.jpg"},
    {"title":"7 Wonders","author":"Antoine Bauza","publisher":"Repos Production","min_players":2,"max_players":7,"play_time_minutes":30,"min_age":10,"complexity":2.3,"category":"Strategy","description":"Civilization card-drafting game about building an ancient wonder.","ownership_status":"wishlist","cover_url":"https://www.myludo.fr/img/jeux/1709818397/jpg/ae/4680.jpg"},
    {"title":"Hive","author":"John Yianni","publisher":"Smart Zone Games","min_players":2,"max_players":2,"play_time_minutes":20,"min_age":9,"complexity":2.3,"category":"Abstract Strategy","description":"Boardless abstract strategy game using insect tiles to surround the opposing queen.","ownership_status":"wishlist","cover_url":"https://cdn.shoplightspeed.com/shops/636231/files/20716066/smart-zone-games-hive-a-game-crawling-with-possibi.jpg"},
    {"title":"Mancala","author":"Traditional","publisher":"Cardinal","min_players":2,"max_players":2,"play_time_minutes":15,"min_age":8,"complexity":1.5,"category":"Abstract Strategy","description":"Traditional count-and-capture game played with stones and rows of pits.","ownership_status":"wishlist","cover_url":"https://i5.walmartimages.com/asr/cfec4fee-e496-4fbc-9985-b432339ed6d5.830f7aaf3326b3ba6494c536410326f9.jpeg?odnBg=FFFFFF&odnHeight=768&odnWidth=768"},
    {"title":"Five Crowns","author":"Marsha J. Falco","publisher":"Set Enterprises","min_players":1,"max_players":7,"play_time_minutes":45,"min_age":8,"complexity":1.2,"category":"Card Game","description":"Five-suited rummy-style card game where wild cards change each round.","ownership_status":"wishlist","cover_url":"https://images.thalia.media/07/-/d582c0b7b361401098202fe1333aff44/five-crowns.jpeg"},
    {"title":"Phase 10","author":"Kenneth Johnson","publisher":"Mattel","min_players":2,"max_players":6,"play_time_minutes":45,"min_age":7,"complexity":1.2,"category":"Card Game","description":"Rummy-style card game about completing ten phases of sets and runs.","ownership_status":"wishlist","cover_url":"https://i2.wp.com/i5.walmartimages.com/asr/ed1f93f9-8201-4cf2-b366-8535c3dffb44.4d5d066061f2ce9798d0868785dc2ebc.jpeg?odnBg=ffffff&odnHeight=1000&odnWidth=1000"},
    {"title":"Spot It!","author":"Denis Blanchot, Jacques Cottereau","publisher":"Zygomatic","min_players":2,"max_players":8,"play_time_minutes":15,"min_age":6,"complexity":1.0,"category":"Party Card Game","description":"Fast visual matching game where every pair of cards shares exactly one symbol.","ownership_status":"wishlist","cover_url":"https://www.bigw.com.au/medias/sys_master/images/images/hf7/hd7/105137534271518.jpg"},
    {"title":"Taco Cat Goat Cheese Pizza","author":"Dave Campbell","publisher":"Dolphin Hat Games","min_players":2,"max_players":8,"play_time_minutes":10,"min_age":8,"complexity":1.0,"category":"Party Card Game","description":"Fast slap-and-match party card game built around a repeating phrase.","ownership_status":"wishlist","cover_url":"https://image.bog-ide.dk/3948395-1467624-1000-787/webp/0/1000/3948395-1467624-1000-787.webp"}
  ]$$::jsonb) as item(
    title text,
    author text,
    publisher text,
    min_players integer,
    max_players integer,
    play_time_minutes integer,
    min_age integer,
    complexity numeric,
    category text,
    description text,
    ownership_status text,
    cover_url text
  )
),
target_library as (
  select id as library_id
  from library.libraries
  where slug = 'jenkins'
)
insert into library.books (
  library_id,
  title,
  author,
  genre,
  description,
  cover_url,
  ownership_status,
  media_type,
  publisher,
  min_players,
  max_players,
  play_time_minutes,
  min_age,
  complexity,
  category
)
select
  target_library.library_id,
  seed.title,
  seed.author,
  seed.category,
  seed.description,
  seed.cover_url,
  seed.ownership_status,
  'board_game',
  seed.publisher,
  seed.min_players,
  seed.max_players,
  seed.play_time_minutes,
  seed.min_age,
  seed.complexity,
  seed.category
from seed, target_library
where not exists (
  select 1
  from library.books existing
  where existing.library_id = target_library.library_id
    and existing.media_type = 'board_game'
    and existing.deleted_at is null
    and lower(existing.title) = lower(seed.title)
);
